app {
  http {
    host = "0.0.0.0"
    port = 8080
    timeout = 40 seconds
  }

  one-frame {
    base-uri = "http://localhost:8080"
    token = "10dc303535874aeccc86a8251e6992f5"
    token = ${?ONE_FRAME_TOKEN_LOCAL}
    timeout = 10 seconds
  }

  cache {
    ttl = 5 minutes
  }

  security {
    max-concurrent-requests = 64
  }
}
